/**
 * Standardized error codes for the Anahata Billing API.
 *
 * Every error response uses one of these codes so integrators can
 * programmatically handle errors without parsing message strings.
 */
export const ErrorCodes = {
  // ── 400 Bad Request ──
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PARAMETER: 'INVALID_PARAMETER',

  // ── 401 Unauthorized ──
  INVALID_API_KEY: 'INVALID_API_KEY',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // ── 403 Forbidden ──
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ORG_ACCESS_DENIED: 'ORG_ACCESS_DENIED',

  // ── 404 Not Found ──
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',

  // ── 405 Method Not Allowed ──
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',

  // ── 409 Conflict ──
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  OPTIMISTIC_LOCK_CONFLICT: 'OPTIMISTIC_LOCK_CONFLICT',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  INVITATION_NOT_PENDING: 'INVITATION_NOT_PENDING',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  // ── 429 Too Many Requests ──
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ── 500 Internal Server Error ──
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  COGNITO_ERROR: 'COGNITO_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
